### ISSUE TITLE
German QA: fix inconsistencies/typos/grammar/...

### ISSUE THREAD

**Issue by Wuzzy2** [MegaGlest/megaglest-data#23]
The German translation was technically complete, but it had a lot of issues which this aims to fix.

I have made a commit which fixes the following:

- Inconsistent unit names in tutorial
- Typos
- Poor grammar
- Just plain wrong translations

You can find the commit here:

http://repo.or.cz/megaglest-data/megaglest-data-wuzzy.git/commit/9f85b9d1e7c6ead2bf44c24b01d77e478db1e4bf

(Sorry, the “Fork” button is broken on GitHub.)

**Comment by tomreyn** [comment]
Merged via bc110bb20dca255f4d4eb6444c1ef3b356fef009 - thank you!
